### ISSUE TITLE
NOAA server cannot be reached

### ISSUE THREAD

**Issue by Jamesrrobbins** [ericpante/marmap#12]
Hi there,
A colleague ran into this issue on the 20th of May 2020, and I also returned this error yesterday. Whenever we run getNOAA.bathy, the call fails as the server cannot be reached. I'm not sure if this is a NOAA issue, or a package issue though. 
Below is the call, and response. 

` bathy <- getNOAA.bathy(lon1 = -23, lon2 = 10,
                         lat1 = 35, lat2 = 66.3, resolution = 4)
Querying NOAA database ...
This may take seconds to minutes, depending on grid size
Error in getNOAA.bathy(lon1 = -23, lon2 = 10, lat1 = 35, lat2 = 66.3,  : 
  The NOAA server cannot be reached`

Thanks for all of your work on this package by the way - it's very useful!

**Comment by besibo** [comment]
Hi,

Have you tried updating `marmap` to v 1.0.4 (available on both GitHub and CRAN)? We had to update `getNOAA.bathy()` to account for a change on NOAA's servers. The method we used to download gridded bathymetry from ETOPO1 on NOAA's servers is not available anymore. Hence the update. You might need to (re)install/update `rgdal` and `raster` as well.

Best

**Comment by Jamesrrobbins** [comment]
Ah that worked - I had to totally uninstall all 3 packages and re-install. Updating them didn't work. Thanks for your help.
