### ISSUE TITLE
error to get data using getNOAA.bathy

### ISSUE THREAD

**Issue by Canales-AguirreCB** [ericpante/marmap#13]
Hi, I'll try to get data from NOAA. I ran the example code from the documentation and an error show up. 
I do not know how fix it or if I doing something wrong. I'm using marmap v1.0.4.

`getNOAA.bathy(lon1=-20,lon2=-90,lat1=50,lat2=20, resolution=10) -> a`

Querying NOAA database ...
This may take seconds to minutes, depending on grid size
Error in if (ncol(x) == 3 & !exists("bathy", inherits = FALSE)) { : 
  argument is of length zero

Any comment to help me with this issue si welcomed
Thanks in advance
Cristian

**Comment by besibo** [comment]
Hi! Have a look here: https://github.com/ericpante/marmap/issues/10#issuecomment-631928645

Best,
Benoit

**Comment by Canales-AguirreCB** [comment]
Thanks a lot!

**Comment by Canales-AguirreCB** [comment]
I didn't realize that I need update the rgdal package.
thank!
