### ISSUE TITLE
NOAA server cannot be reached

### ISSUE THREAD

**Issue by dswdejonge** [ericpante/marmap#14]
Hi there!

The function getNOAA.bathy worked beautifully until a couple of weeks ago. Now I get the error:

```r
Error in marmap::getNOAA.bathy(lon1 = lon1, lon2 = lon2, lat1 = lat1,  : 
  The NOAA server cannot be reached
```

Is the link in 'fetch' still up to date?

**Comment by besibo** [comment]
You need to update marmap to v 1.0.4
