### ISSUE TITLE
getNOAA.bathy: path length (Windows)

### ISSUE THREAD

**Issue by dswdejonge** [ericpante/marmap#15]
Hi!

I was getting the following error on a Windows machine when using the function getNOAA.bathy:

```
Error in if (ncol(x) == 3 & !exists("bathy", inherits = FALSE)) { : 
  argument is of length zero
```

I figured fetching the data did not work, and debugging gave me the the actual problem:

```
"Error in basename(x) : path too long\n"
```
The url created with paste that gave this error was:
"https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/ETOPO1_bedrock/ImageServer/exportImage?bbox=-0.58,51.0459,7.24046,60.42&bboxSR=4326&size=469.2276,562.446&imageSR=4326&format=tiff&pixelType=S16&interpolation=+RSP_NearestNeighbor&compression=LZW&f=image"
which is 262 characters long, whereas the maximum path length allowed by Windown is 260.
I fixed this by always capping the lat and long to 1 decimal place.

Just wanted to let you know this issue occurred, so perhaps you can fix it or provide a more insightful error when this issue occurs.

Great package, thanks! :)

**Comment by besibo** [comment]
Thanks for your very useful feedback. I'll look into it as soon as I can get my hands on a windows PC!
Best,
Benoit

**Comment by besibo** [comment]
I've updated `getNOAA.bathy()` to shorten the URL of the web request we send to NOAA servers by dropping unnecessary decimals. This should solve the issue. I'll push the update to CRAN ASAP.
