### ISSUE TITLE
HTTP error code : 404

### ISSUE THREAD

**Issue by ghost** [ericpante/marmap#18]
Hi! After loading marmap and running these lines from Rstudio ver. 1.4.1103 (R ver. x64 4.0.3)

library(marmap)

W_coast<-getNOAA.bathy(lon1=-126, lon2=-124, lat1= 40, lat2=45.5, resolution=1)

I get this error:

Querying NOAA database ...
This may take seconds to minutes, depending on grid size
Error in .local(.Object, ...) : HTTP error code : 404

Error in if (ncol(x) == 3 & !exists("bathy", inherits = FALSE)) { : 
  argument is of length zero

I appreciate any help you can provide with this-Marco

**Comment by besibo** [comment]
Found on NOAA's website:

```
2021-01-20: Due to scheduled system maintenance, ngdc.noaa.gov services will be unavailable from
Wednesday 2021-01-20 16:00 MT until Friday 2021-01-22 12:00 MT.
```

Things should be back to normal soon.

**Comment by ghost** [comment]
thank you so much!
