### ISSUE TITLE
dislaying nicely in 3D

### ISSUE THREAD

**Issue by helgasoft** [ericpante/marmap#22]
Thank you for the great library!  Was searching for such solution for a some time.
Marmap integrates successfully with our [echarty](https://github.com/helgasoft/echarty)  to show bathymetry in 3D.
To see the demo:
```r
runGist('https://gist.github.com/helgasoft/121d7d3ff7d292990c3e05cfc1cbf24b')
```
No problems encountered so far 👍

**Comment by besibo** [comment]
Glad to hear it! I tried to play with echarty (seems great!), but got an error every time: "Error: unused argument (header = FALSE)"

**Comment by ericpante** [comment]
Hi!  Same thing here. 
Cheers, Eric

**Comment by helgasoft** [comment]
Yes, the current CRAN version is 0.1.0 and does not have the *header* attribute. You'll need the development version 0.1.3
```r
# install.packages("remotes")
remotes::install_github("helgasoft/echarty")     # v.0.1.3
```
Sorry for the inconvenience. We have to resubmit to CRAN to make this available to a wider audience.

**Comment by besibo** [comment]
Works great, thanks a lot!
