### ISSUE TITLE
HTTP error code : 500

### ISSUE THREAD

**Issue by pfeutry** [ericpante/marmap#23]
Hi there, I had this code from 2-3 years ago I've tried to re-run but I keep getting this error. Note that I had a slightly different error before I updated raster and rgdal.
I am running marmap 1.0.5 on a Mac using Rstudio and R 4.0.5

> IO.5 <- getNOAA.bathy(lon1 = 112, lon2 = 155, lat1 = -25, lat2 = -8, resolution = 5)
Querying NOAA database ...
This may take seconds to minutes, depending on grid size
Error in .local(.Object, ...) : HTTP error code : 500

Error in if (ncol(x) == 3 & !exists("bathy", inherits = FALSE)) { : 
  argument is of length zero

Thanks for any pointers on how to fix this.

**Comment by besibo** [comment]
This seems to be a problem on NOAA's servers. If you go [here](https://maps.ngdc.noaa.gov/viewers/grid-extract/index.html) to manually download bathymetric data from the ETOPO1 database, your query will be stuck for a while, and you'll get the same `Error 500` message. `marmap::getNOAA.bathy()` juste provides a convient way to construct queries  to the ETOPO1 database hosted on NOAA's server from within `R`. 
So there's nothing I can do here. I guess the problem will solve itself when the bug on NOAA's servers is sorted out.

**Comment by abfleishman** [comment]
@mgilmour was having this issue last Thursday and when we changed the resolution to a number >1 it worked including when we changed the resolution to 1.01.  Not sure what that might mean but figured I would chime in.

**Comment by besibo** [comment]
@abfleishman Hum... Doesn't seem to be related. The following code from @pfeutry's post above now works as expected (June 1st, 2021, 17:39 UTC):

    IO.5 <- getNOAA.bathy(lon1 = 112, lon2 = 155, lat1 = -25, lat2 = -8, resolution = 5)

I guess NOAA's servers are back on track!

**Comment by pfeutry** [comment]
working now woop woop, thanks everyone! My R skills are relatively poor, so every time an R issue is not a user issue I take it like a small victory.
