### ISSUE TITLE
lc.dist reports in km -- is it possible to report at meters?

### ISSUE THREAD

**Issue by gsrednick** [ericpante/marmap#24]
I am using lc.dist to measure distance between sites over-water. However, some of these sites are relatively close together (< 1 km). Is it possible to have lc.dist report in meters or perhaps report multiple decimal places? Obviously converting to meters from km when there are no decimal places after the fact is not a useful method.

Thank you!

**Comment by besibo** [comment]
I just updated the `lc.dist()` function with 2 new arguments to allow the computation of distances in meters and with a user defined rounding. Available now on github in marmap v1.0.6, and submitted to CRAN this morning. 

Please let me know if it works for you.
Best

**Comment by gsrednick** [comment]
Working. Thanks Benoit!
