### ISSUE TITLE
Problem with NOAA server?

### ISSUE THREAD

**Issue by richardsc** [ericpante/marmap#27]
Hi!

It looks like there might be an issue with the NOAA server? Not sure if it's a temporary outage or some permanent change.

```r
library(marmap)
b <- getNOAA.bathy(-60, -55, 40, 45)
```
```
Querying NOAA database ...
This may take seconds to minutes, depending on grid size
Error in .local(.Object, ...) :

Error in if (ncol(x) == 3 & !exists("bathy", inherits = FALSE)) { :
  argument is of length zero
```

Results from `sessionInfo()`:
```
R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.3.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] marmap_1.0.6 oce_1.7-3    gsw_1.0-7

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8          pillar_1.6.4        compiler_4.1.2
 [4] plyr_1.8.6          tools_4.1.2         bit_4.0.4
 [7] ncdf4_1.18          memoise_2.0.1       RSQLite_2.2.9
[10] lifecycle_1.0.1     tibble_3.1.6        gtable_0.3.0
[13] lattice_0.20-45     pkgconfig_2.0.3     rlang_1.0.1
[16] DBI_1.1.1           cli_3.1.0           rgdal_1.5-28
[19] fastmap_1.1.0       terra_1.4-22        dplyr_1.0.7
[22] stringr_1.4.0       raster_3.5-9        generics_0.1.1
[25] vctrs_0.3.8         bit64_4.0.5         grid_4.1.2
[28] tidyselect_1.1.1    glue_1.6.1          R6_2.5.1
[31] fansi_0.5.0         sp_1.4-6            adehabitatMA_0.3.14
[34] blob_1.2.2          ggplot2_3.3.5       purrr_0.3.4
[37] reshape2_1.4.4      magrittr_2.0.2      scales_1.1.1
[40] codetools_0.2-18    ellipsis_0.3.2      assertthat_0.2.1
[43] shape_1.4.6         colorspace_2.0-2    utf8_1.2.2
[46] stringi_1.7.6       munsell_0.5.0       cachem_1.0.6
[49] crayon_1.5.0
```

**Comment by besibo** [comment]
This should be only temporary and everything should go back to normal in a few days. Details here: https://www.ngdc.noaa.gov/index.html.

To avoid such problems, don't hesitate to set `keep = TRUE` in `getNOAA.bathy()` to save/load local copies of your bathymetries.

**Comment by richardsc** [comment]
Oh, thanks for that update. I looked around but didn't find that page. 

And yes, I often use `keep=TRUE` but this was a new analysis region. 

Thanks for the great package!

**Comment by chris-english** [comment]
As different from the above #27 and oce#1938 as to output following up on [SOF response](https://stackoverflow.com/questions/73582299/creating-bathymetric-lines-from-getnoaa-bathy-and-add-them-to-ggplot-how-do-i-h?noredirect=1#comment129944022_73582299):
bat <- getNOAA.bathy(-12, -5, 35, 44, res = 4, keep = TRUE)
Querying NOAA database ...
This may take seconds to minutes, depending on grid size
Error in if (ncol(x) == 3 & !exists("bathy", inherits = FALSE)) { : 
  argument is of length zero

So no reference to 
Error in .local(.Object, ...) : 
prior to 
Error in if (ncol(x) == 3 & !exists("bathy", inherits = FALSE)) { : 
  argument is of length zero

And seemingly no reference to maintenance at NOAA site.

**Comment by besibo** [comment]
Have you [tried this](https://github.com/ericpante/marmap/issues/25#issuecomment-965834490) ?

**Comment by chris-english** [comment]
My raster: 3.6.0, so no longer uses _rgdal_ or _rgeos_, 
that is the trajectory of the R spatial stack, so I'll fish around
for a _download.file_ that works in this context and report if
successful. I imagine you will be doing the 
same soon.

**Comment by besibo** [comment]
Yes, I knew the change was imminent and I have to update several functions to get rid of old/deprecated dependencies. It is definitely on our schedule, but due to time constraints, I won't be able to look into it for at least several weeks. I'll report back here when it's done. Thanks for the feedback!

**Comment by raorben** [comment]
It looks like the NOAA server might be down again? Though I was also wondering if links may have changed with the launch of ETOPO 2022 at the end of October?
https://www.ncei.noaa.gov/products/etopo-global-relief-model

**Comment by besibo** [comment]
`getNOAA.bathy()` working as usual on my side. Do you still have trouble downloading data?

In the next version of marmap, I'll try to update `getNOAA.bathy()` anyway to use the higher resolution of the ETOPO 2022 dataset instead of ETOPO 1. Thanks for the pointer!

**Comment by besibo** [comment]
I've updated `getNOAA.bathy()` to take advantage of the new ETOPO 2022 database, with resolution of up to 15 arcseconds (set `res = 0.25` or `res=0.5` to use the higher resolutions offered by ETOPO 2022). `marmap v1.0.7` is already available on github and should be uploaded on CRAN servers in the new few days.

**Comment by raorben** [comment]
Awesome! Thank you. getNOAA.bathy() worked just fine when I tried it again.
