### ISSUE TITLE
getNOAAbathy() connection issue

### ISSUE THREAD

**Issue by krtanaka** [ericpante/marmap#31]
Hello 

I just noticed that getNOAA.bathy() is now returning some sort of connection issue. At least one other user at my institution is reporting the same error. Please see below: 

> getNOAA.bathy(lon1=-20,lon2=-90,lat1=50,lat2=20, resolution=10) -> a
Querying NOAA database ...
This may take seconds to minutes, depending on grid size

trying URL 'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_all/ImageServer/exportImage?bbox=-90,20,-20,50&bboxSR=4326&size=420,180&imageSR=4326&format=tiff&pixelType=F32&interpolation=+RSP_NearestNeighbor&compression=LZ77&renderingRule={%22rasterFunction%22:%22none%22}&mosaicRule={%22where%22:%22Name=%27ETOPO_2022_v1_60s_bed%27%22}&f=image'
Error in download.file(url = WEB.REQUEST, destfile = "tmp.tif", mode = "wb") : 
  cannot open URL 'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_all/ImageServer/exportImage?bbox=-90,20,-20,50&bboxSR=4326&size=420,180&imageSR=4326&format=tiff&pixelType=F32&interpolation=+RSP_NearestNeighbor&compression=LZ77&renderingRule={%22rasterFunction%22:%22none%22}&mosaicRule={%22where%22:%22Name=%27ETOPO_2022_v1_60s_bed%27%22}&f=image'
In addition: Warning message:
In download.file(url = WEB.REQUEST, destfile = "tmp.tif", mode = "wb") :
  URL 'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_all/ImageServer/exportImage?bbox=-90,20,-20,50&bboxSR=4326&size=420,180&imageSR=4326&format=tiff&pixelType=F32&interpolation=+RSP_NearestNeighbor&compression=LZ77&renderingRule={%22rasterFunction%22:%22none%22}&mosaicRule={%22where%22:%22Name=%27ETOPO_2022_v1_60s_bed%27%22}&f=image': status was 'SSL connect error'

**Comment by besibo** [comment]
Do you still get the same error? I have no problem downloading the dataset from R and even clicking the url in your post downloads the correct data in a web browser. Maybe NOAA's servers were offline for a while? Or your internet connection was down?
