### ISSUE TITLE
warnings in get.area()

### ISSUE THREAD

**Issue by d-lorenz** [ericpante/marmap#5]
Hello Eric!

I am getting these warnings when computing the projected surface area for the depth layer (ex. 10 - 100). It could be a specific problem of my systems, but I get the same warnings on both OS and Ubuntu. I think it is better to inform you.

> data(aleutians)
> marmap::get.area(aleutians, level.inf=-100,  level.sup=-10)
>**There were 50 or more warnings (use warnings() to see the first 50)**

> warnings()
>**Warning messages: 1: In .local(x, ...) : remove argument "r" to use an better algorithm**

However, I would like to assume the returned values are correct and not affected by the warnings.

Many thanks for your help and, in general, for the wonderful package you and your team have built!

Best,
Lorenzo

**Comment by ericpante** [comment]
Hi Lorenzo, 

Thanks for your message. I have several big deadlines today so I cannot have a detailed look into the issue, but here are some elements of response - perhaps Benoit can confirm. 

function `get.area` depends on another function called `areaPolygon` from package `geosphere`
`areaPolygon` has been modified, so I have changed `get.area` accordingly so that the arguments remain compatible. The function now returns the same result (I have checked with the hawaii dataset) and is over twice as fast. An there are no warnings. 

Here it is: 

`get.area2 <- function (mat, level.inf, level.sup = 0, xlim = NULL, ylim = NULL) 
{
    if (!is(mat, "bathy") & !is(mat, "buffer")) 
        stop("mat must be of class 'bathy' or 'buffer'")
    if (is(mat, "buffer")) 
        mat <- mat[[1]]
    lon <- as.numeric(rownames(mat))
    lat <- as.numeric(colnames(mat))
    if (is.null(xlim)) 
        xlim <- range(lon)
    if (is.null(ylim)) 
        ylim <- range(lat)
    if (any(is.na(mat))) 
        mat[is.na(mat)] <- 1e+05 * max(mat, na.rm = TRUE)
    x1b <- which.min(abs(lon - xlim[1]))
    y1b <- which.min(abs(lat - ylim[1]))
    x2b <- which.min(abs(lon - xlim[2]))
    y2b <- which.min(abs(lat - ylim[2]))
    mat <- mat[x1b:x2b, y1b:y2b]
    lon <- as.numeric(rownames(mat))
    lat <- as.numeric(colnames(mat))
    cell.width <- (lon[2] - lon[1])
    cell.height <- (lat[2] - lat[1])
    bathy2 <- ifelse(mat >= level.inf & mat <= level.sup, 1, 
        0)
    cells <- apply(bathy2, 2, sum)
    cells <- cells[cells != 0]
    c.lat <- as.numeric(names(cells))
    poly <- list()
    for (i in 1:length(cells)) poly[[i]] <- rbind(c(0, c.lat[i]), 
        c(0, c.lat[i] + cell.height), c(cells[i] * cell.width, 
            c.lat[i] + cell.height), c(cells[i] * cell.width, 
            c.lat[i]))
    surf <- sum(sapply(poly, geosphere::areaPolygon, a=6378137, f=1/298.257223563))
    return <- list(Square.Km = surf, Area = bathy2, Lon = lon, 
        Lat = lat)
}`

We will do a more in-depth check and post the change on GitHub. 
Thanks again for letting us know of the issue !!

All the best, eric

**Comment by d-lorenz** [comment]
That was quick!

I have loaded your prototype function get.area2().
Maybe you already know it but, while comparing the previous version of get.area(), I am getting a very similar result: 

dataset | get.area() | get.area2()
------------ | ------------ | -------------
aleutians | 787883.7 | 792264937789
test_data | 38861.65 | 38875218345

As these values are 10E6 greater, I suppose the output of the earlier version of areaPolygon were in km^2 and now in m^2 ?

Just contributing to the discussion, I understand your deadlines and I will wait without pressing!

Thank you again! 

Best,
Lorenzo

**Comment by ericpante** [comment]
Hi Lorenzo, 
Indeed you are right! the unit has been changed (in the `geosphere` package) to square meters . 
We'll have to modify the `marmap` documentation accordingly. 
Thanks! 
eric

**Comment by besibo** [comment]
Hi to the two of you!

> Indeed you are right! the unit has been changed (in the geosphere package) to square meters .
> We'll have to modify the marmap documentation accordingly.
> 
Or modify get.area() so that the output of the function is not affected by the change in the geosphere package! ;-)

**Comment by ericpante** [comment]
or that! ;-)

**Comment by besibo** [comment]
Hey guys,

The new get.area() is now available on github. And the output is back in km^2.

Best,
Benoit

**Comment by d-lorenz** [comment]
Thank you Benoit and Eric!

I would like to ask if the usage is the same or is changed?

Best,
Lorenzo

**Comment by besibo** [comment]
Nothing changed from the user perspective. Same arguments, same outputs (expect for the improved speed and precision due to the new way areaPolygon from package geosphere now performs the computations).

Best,
Benoit
