### ISSUE TITLE
Messages are provided using cat rather than message

### ISSUE THREAD

**Issue by DanielReedOcean** [ericpante/marmap#6]
This is an incredibly useful package. Kudos for writing it! I am, however, running into one persistent issue with messages that are issued by `getNOAA.bathy`. I noticed that you use `cat` to output messages (e.g., `File already exists...`) and, as a result, these outputs are not treated as regular messages. This means that they do not play nicely with functions like `base::suppressMessages`. Would it be possible to switch from using `cat` to `message` in a future version of `marmap`?

**Comment by ericpante** [comment]
Hi Dan, 

Thanks for your message, and for your suggestion !! 
We will make the change asap.

Cheers, eric

**Comment by besibo** [comment]
I'm already on it. The changes will be made available on github in a few minutes. I'll submit a new version to CRAN in a few days.

Best,
Benoit

**Comment by DanielReedOcean** [comment]
Thanks for the quick response – it's much appreciated!
