### ISSUE TITLE
Persisting problem with getNOAA.bathy

### ISSUE THREAD

**Issue by ydorant** [ericpante/marmap#7]
Hi,
I observed a persisting error with the function getNOAA,bathy() with MARMAP. Even if I use the update of 15 oct 2018...
_Error in getNOAA.bathy2(lon1 = -58, lon2 = -66, lat1 = 44, lat2 = 50,  : 
  The NOAA server cannot be reached_

Did the NOAA server address changed again ? Could you verify if you can access it on your side ?
Thanks!
Yann,

**Comment by besibo** [comment]
Hello Yann,

I suppose it is due to the government shutdown: https://www.noaa.gov/
Let’s hope it will be resolved soon...

Best

-- 
Benoit Simon-Bouhet

Le 28 décembre 2018 à 19:37:57, ydorant (notifications@github.com) a écrit:

**Comment by tahamimo** [comment]
Hi,
I have the package load error which therefore fails to execute the 'space.pies' function:

> library(marmap)
Error: package or namespace load failed for ‘marmap’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.4.1 is already loaded, but >= 0.4.2 is required
In addition: Warning message:
package ‘marmap’ was built under R version 3.6.3 

tried to update the package 'rlang' separately, didn't work

**Comment by besibo** [comment]
Dear tahamino (Masse),

You can't continue to post the same message again and again, on Github, on Stackoverflow, or by direct email to the maintainer of the marmap package (that's me by the way), if you don't even bother to test the solutions we suggest.

I already advised you both by email and on StackOverfolw to:
1. Shutdown R
2. Launch a new R session
3. Type `install.packages("rlang")` and
4. Tell us if the rlang installation process went well or report any error messages you may have encountered. 

So far, I've had not heard back from you...

As already explained several times, this is not a `marmap` related issue! At this point, there is not much more I or Eric could do to solve your problem. Help us help you! Or stop posting...

Best,
Benoit
