### ISSUE TITLE
Select path in getNOAA.bathy

### ISSUE THREAD

**Issue by jmburgos** [ericpante/marmap#8]
Hi,
It would be useful if we could select the path where the getNOAA,bathy function writes (and reads, if the file is present) the data donwloaded from the ETOPO database.  Now the function donwloads the file in the working directory, which is not optimal.  It would be better if we could point the function to a particular folder.

Thanks!

**Comment by besibo** [comment]
Great suggestion! I'll be sure to include this modification to `getNOAA.bathy()` in the next update. Thanks for your feedback..

**Comment by besibo** [comment]
Hi @jmburgos! 

I just added a `path` argument to `getNOAA.bathy()` and modified the function to acknowledge the change in NOAA's way of providing gridded bathymetric data. It should work as expected, at least on Linux/MacOS: just provide a valid path to a folder where you want the function to write (or look for available) bathymetric data. I don't have a windows machine available for testing right now, so I welcome any feedback!

Best

**Comment by jmburgos** [comment]
Thanks, it works nicely! I also work in Linux, so I cannot test it under Windows.
